### ISSUE TITLE
Ransomware

### ISSUE THREAD

**Issue by ComradeJarif** [Aldrin-John-Olaer-Manalansan/RA2YR-MIX-Unprotector-MASTER#1]
Windows Defender marks the `.zip` as a ransomware

**Comment by Aldrin-John-Olaer-Manalansan** [comment]
> Windows Defender marks the `.zip` as a ransomware

A quick tip before suspecting wether an app is malicious or not:
1. An application this simple is most likely be malicious if the developer hides its source code to the public eye. Which is completely opposite for this app's case.
2. As you can already tell, this application is [Open Source](https://github.com/Aldrin-John-Olaer-Manalansan/RA2YR-MIX-Unprotector-MASTER/blob/master/AJOM%20Innovations/RA2YR%20MIX%20Unprotector%20Master/Source%20Code/RA2YR%20MIX%20Unprotector%20Master.ahk) because this app has no malice to hide towards the public.

It is better for you to look at the [source code](https://github.com/Aldrin-John-Olaer-Manalansan/RA2YR-MIX-Unprotector-MASTER/blob/master/AJOM%20Innovations/RA2YR%20MIX%20Unprotector%20Master/Source%20Code/RA2YR%20MIX%20Unprotector%20Master.ahk) and check for any malicious activities. That way you'll be able to tell wether you should trust this App that I created or not.

Closed.

**Comment by Aldrin-John-Olaer-Manalansan** [comment]
> Windows Defender marks the `.zip` as a ransomware

A quick tip before suspecting wether an app is malicious or not:
1. An application this simple is most likely be malicious if the developer hides its source code to the public eye. Which is completely opposite for this app's case.
2. As you can already tell, this application is [Open Source](https://github.com/Aldrin-John-Olaer-Manalansan/RA2YR-MIX-Unprotector-MASTER/blob/master/AJOM%20Innovations/RA2YR%20MIX%20Unprotector%20Master/Source%20Code/RA2YR%20MIX%20Unprotector%20Master.ahk) because this app has no malice to hide towards the public.

It is better for you to look at the [source code](https://github.com/Aldrin-John-Olaer-Manalansan/RA2YR-MIX-Unprotector-MASTER/blob/master/AJOM%20Innovations/RA2YR%20MIX%20Unprotector%20Master/Source%20Code/RA2YR%20MIX%20Unprotector%20Master.ahk) and check for any malicious activities. That way you'll be able to tell wether you should trust this App that I created or not.

Closed.

**Comment by ComradeJarif** [comment]
> A quick tip before suspecting wether an app is malicious or not:

Hello

I am not the most... uh, I guess "techy" person. 

I installed the thing and Windows Defender immediately alerted me of it being a ransomware. Now, I do know that some stuff acts like a ransomware (IIRC, Syringe from CnCNet/Ares does) in order to actually work, but I was just not fully sure. So, I figured I'd ask you here. 

Anyways, thanks.
